export type BorderingCountries = { [s: string]: string[] };
const borderingCountries: BorderingCountries = {
  Abkhazia: ["Russia", "Georgia"],
  Afghanistan: [
    "People's Republic of China",
    "Iran",
    "Pakistan",
    "Tajikistan",
    "Turkmenistan",
    "Uzbekistan",
  ],
  Albania: ["Greece", "Kosovo", "North Macedonia", "Montenegro"],
  Algeria: [
    "Libya",
    "Mali",
    "Mauritania",
    "Morocco",
    "Niger",
    "Tunisia",
    "Western Sahara",
  ],
  Andorra: ["France", "Spain"],
  Angola: [
    "Democratic Republic of the Congo",
    "Republic of the Congo",
    "Namibia",
    "Zambia",
  ],
  "Antigua and Barbuda": [""],
  Argentina: ["Bolivia", "Brazil", "Chile", "Paraguay", "Uruguay"],
  Armenia: ["Azerbaijan", "Georgia", "Iran", "Turkey"],
  Australia: [""],
  Austria: [
    "Czech Republic",
    "Germany",
    "Hungary",
    "Italy",
    "Liechtenstein",
    "Slovakia",
    "Slovenia",
    "Switzerland",
  ],
  Azerbaijan: ["Armenia", "Georgia", "Iran", "Russia", "Turkey"],
  Bahamas: [""],
  Bahrain: [""],
  Bangladesh: ["India", "Myanmar"],
  Barbados: [""],
  Belarus: ["Latvia", "Lithuania", "Poland", "Russia", "Ukraine"],
  Belgium: ["France", "Germany", "Luxembourg", "Netherlands"],
  Belize: ["Guatemala", "Mexico"],
  Benin: ["Burkina Faso", "Niger", "Nigeria", "Togo"],
  Bhutan: ["People's Republic of China", "India"],
  Bolivia: ["Argentina", "Brazil", "Chile", "Paraguay", "Peru"],
  "Bosnia and Herzegovina": ["Croatia", "Montenegro", "Serbia"],
  Botswana: ["Namibia", "South Africa", "Zambia", "Zimbabwe"],
  Brazil: [
    "Argentina",
    "Bolivia",
    "Colombia",
    "French Guiana",
    "Guyana",
    "Paraguay",
    "Peru",
    "Suriname",
    "Uruguay",
    "Venezuela",
  ],
  Brunei: ["Malaysia"],
  Bulgaria: ["Greece", "North Macedonia", "Romania", "Serbia", "Turkey"],
  "Burkina Faso": ["Benin", "Côte d'Ivoire", "Ghana", "Mali", "Niger", "Togo"],
  Burundi: ["Democratic Republic of the Congo", "Rwanda", "Tanzania"],
  Cambodia: ["Laos", "Thailand", "Vietnam"],
  Cameroon: [
    "Central African Republic",
    "Chad",
    "Republic of the Congo",
    "Equatorial Guinea",
    "Gabon",
    "Nigeria",
  ],
  Canada: ["United States"],
  "Cape Verde": [""],
  "Central African Republic": [
    "Cameroon",
    "Chad",
    "Democratic Republic of the Congo",
    "Republic of the Congo",
    "South Sudan",
    "Sudan",
  ],
  Chad: [
    "Cameroon",
    "Central African Republic",
    "Libya",
    "Niger",
    "Nigeria",
    "Sudan",
  ],
  Chile: ["Argentina", "Bolivia", "Peru"],
  "People's Republic of China[17]": [
    "Afghanistan",
    "Bhutan",
    "India",
    "Kazakhstan",
    "North Korea",
    "Kyrgyzstan",
    "Laos",
    "Mongolia",
    "Myanmar",
    "Nepal",
    "",
    "",
    "Pakistan",
    "Russia",
    "Tajikistan",
    "Vietnam",
  ],
  Colombia: ["Brazil", "Ecuador", "Panama", "Peru", "Venezuela"],
  Comoros: [""],
  "Democratic Republic of the Congo": [
    "Angola",
    "Burundi",
    "Central African Republic",
    "Republic of the Congo",
    "Rwanda",
    "South Sudan",
    "Tanzania",
    "Uganda",
    "Zambia",
  ],
  "Republic of the Congo": [
    "Angola",
    "Cameroon",
    "Central African Republic",
    "Democratic Republic of the Congo",
    "Gabon",
  ],
  "Costa Rica": ["Nicaragua", "Panama"],
  "Côte d'Ivoire": ["Burkina Faso", "Ghana", "Guinea", "Liberia", "Mali"],
  Croatia: [
    "Bosnia and Herzegovina",
    "Hungary",
    "Montenegro",
    "Serbia",
    "Slovenia",
  ],
  Cuba: [""],
  Cyprus: ["Akrotiri and Dhekelia"],
  "Czech Republic": ["Austria", "Germany", "Poland", "Slovakia"],
  Denmark: ["Germany"],
  Djibouti: ["Eritrea", "Ethiopia", "Somaliland"],
  Dominica: [""],
  "Dominican Republic": ["Haiti"],
  "East Timor": ["Indonesia"],
  Ecuador: ["Colombia", "Peru"],
  Egypt: ["Gaza Strip (State of Palestine)", "Israel", "Libya", "Sudan"],
  "El Salvador": ["Guatemala", "Honduras"],
  "Equatorial Guinea": ["Cameroon", "Gabon"],
  Eritrea: ["Djibouti", "Ethiopia", "Sudan"],
  Estonia: ["Latvia", "Russia"],
  Eswatini: ["Mozambique", "South Africa"],
  Ethiopia: ["Djibouti", "Eritrea", "Kenya", "Somalia", "South Sudan", "Sudan"],
  Fiji: [""],
  Finland: ["Norway", "Sweden", "Russia"],
  France: [
    "Andorra",
    "Belgium",
    "Germany",
    "Italy",
    "Luxembourg",
    "Monaco",
    "Spain",
    "Switzerland",
  ],
  "France with colonies": [
    "Andorra",
    "Belgium",
    "Brazil",
    "Germany",
    "Italy",
    "Luxembourg",
    "Monaco",
    "Sint Maarten",
    "Spain",
    "Suriname",
    "Switzerland",
  ],
  Gabon: ["Cameroon", "Republic of the Congo", "Equatorial Guinea"],
  "The Gambia": ["Senegal"],
  Georgia: [
    "Armenia",
    "Azerbaijan",
    "Russia",
    "Turkey",
    "Abkhazia",
    "South Ossetia",
  ],
  Germany: [
    "Austria",
    "Belgium",
    "Czech Republic",
    "Denmark",
    "France",
    "Luxembourg",
    "Netherlands",
    "Poland",
    "Switzerland",
  ],
  Ghana: ["Burkina Faso", "Côte d'Ivoire", "Togo"],
  Greece: ["Albania", "Bulgaria", "Turkey", "North Macedonia"],
  Grenada: [""],
  Guatemala: ["Belize", "El Salvador", "Honduras", "Mexico"],
  Guinea: [
    "Côte d'Ivoire",
    "Guinea-Bissau",
    "Liberia",
    "Mali",
    "Senegal",
    "Sierra Leone",
  ],
  "Guinea-Bissau": ["Guinea", "Senegal"],
  Guyana: ["Brazil", "Suriname", "Venezuela"],
  Haiti: ["Dominican Republic"],
  Honduras: ["Guatemala", "El Salvador", "Nicaragua"],
  "Hong Kong[29]": ["People's Republic of China"],
  Hungary: [
    "Austria",
    "Croatia",
    "Romania",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Ukraine",
  ],
  Iceland: [""],
  India: [
    "Bangladesh",
    "Bhutan",
    "People's Republic of China",
    "Myanmar",
    "Nepal",
    "Pakistan",
    "Sri Lanka",
  ],
  Indonesia: ["East Timor", "Malaysia", "Papua New Guinea"],
  Iran: [
    "Afghanistan",
    "Armenia",
    "Azerbaijan",
    "Iraq",
    "Pakistan",
    "Turkey",
    "Turkmenistan",
  ],
  Iraq: ["Iran", "Jordan", "Kuwait", "Saudi Arabia", "Syria", "Turkey"],
  Ireland: ["United Kingdom"],
  Israel: [
    "Egypt",
    "Gaza Strip (State of Palestine)",
    "Jordan",
    "Lebanon",
    "Syria",
    "West Bank (State of Palestine)",
  ],
  Italy: [
    "Austria",
    "France",
    "San Marino",
    "Slovenia",
    "Switzerland",
    "Vatican City",
  ],
  Jamaica: [""],
  Japan: [""],
  Jordan: [
    "Iraq",
    "Israel",
    "Saudi Arabia",
    "Syria",
    "West Bank (State of Palestine)",
  ],
  Kazakhstan: [
    "People's Republic of China",
    "Kyrgyzstan",
    "Russia",
    "Turkmenistan",
    "Uzbekistan",
  ],
  Kenya: ["Ethiopia", "Somalia", "South Sudan", "Tanzania", "Uganda"],
  Kiribati: [""],
  "North Korea": ["People's Republic of China", "South Korea", "Russia"],
  "South Korea": ["North Korea"],
  Kosovo: ["Albania", "Montenegro", "North Macedonia", "Serbia"],
  Kuwait: ["Iraq", "Saudi Arabia"],
  Kyrgyzstan: [
    "People's Republic of China",
    "Kazakhstan",
    "Tajikistan",
    "Uzbekistan",
  ],
  Laos: [
    "Cambodia",
    "People's Republic of China",
    "Myanmar",
    "Thailand",
    "Vietnam",
  ],
  Latvia: ["Belarus", "Estonia", "Lithuania", "Russia"],
  Lebanon: ["Israel", "Syria"],
  Lesotho: ["South Africa"],
  Liberia: ["Guinea", "Côte d'Ivoire", "Sierra Leone"],
  Libya: ["Algeria", "Chad", "Egypt", "Niger", "Sudan", "Tunisia"],
  Liechtenstein: ["Austria", "Switzerland"],
  Lithuania: ["Belarus", "Latvia", "Poland", "Russia"],
  Luxembourg: ["Belgium", "France", "Germany"],
  Macau: ["People's Republic of China"],
  Madagascar: [""],
  Madeira: [""],
  Malawi: ["Mozambique", "Tanzania", "Zambia"],
  Malaysia: ["Brunei", "Indonesia", "Thailand"],
  Maldives: [""],
  Mali: [
    "Algeria",
    "Burkina Faso",
    "Côte d'Ivoire",
    "Guinea",
    "Mauritania",
    "Niger",
    "Senegal",
  ],
  Malta: [""],
  "Marshall Islands": [""],
  Mauritania: ["Algeria", "Mali", "Senegal", "Western Sahara"],
  Mauritius: [""],
  Mexico: ["Belize", "Guatemala", "United States"],
  "Federated States of Micronesia": [""],
  Moldova: ["Romania", "Ukraine"],
  Monaco: ["France"],
  Mongolia: ["People's Republic of China", "Russia"],
  Montenegro: [
    "Albania",
    "Bosnia and Herzegovina",
    "Croatia",
    "Kosovo",
    "Serbia",
  ],
  Morocco: ["Algeria", "Western Sahara", "Spain"],
  Mozambique: [
    "Eswatini",
    "Malawi",
    "South Africa",
    "Tanzania",
    "Zambia",
    "Zimbabwe",
  ],
  Myanmar: [
    "Bangladesh",
    "People's Republic of China",
    "India",
    "Laos",
    "Thailand",
  ],
  Namibia: ["Angola", "Botswana", "South Africa", "Zambia"],
  Nauru: [""],
  Nepal: ["People's Republic of China", "India"],
  "Netherlands\nshow\n→includes:": ["Belgium", "Germany", "Saint Martin"],
  "New Zealand": [""],
  Nicaragua: ["Costa Rica", "Honduras"],
  Niger: [
    "Algeria",
    "Benin",
    "Burkina Faso",
    "Chad",
    "Libya",
    "Mali",
    "Nigeria",
  ],
  Nigeria: ["Benin", "Cameroon", "Chad", "Niger"],
  "North Macedonia": ["Albania", "Bulgaria", "Greece", "Kosovo", "Serbia"],
  Norway: ["Finland", "Sweden", "Russia"],
  Oman: ["Saudi Arabia", "United Arab Emirates", "Yemen"],
  Pakistan: ["Afghanistan", "India", "Iran", "People's Republic of China", ""],
  Palau: [""],
  "Palestine[22]": ["Egypt", "Israel", "Jordan"],
  Panama: ["Colombia", "Costa Rica"],
  "Papua New Guinea": ["Indonesia"],
  Paraguay: ["Argentina", "Bolivia", "Brazil"],
  Peru: ["Bolivia", "Brazil", "Chile", "Colombia", "Ecuador"],
  Philippines: [""],
  Poland: [
    "Belarus",
    "Czech Republic",
    "Germany",
    "Lithuania",
    "Russia",
    "Slovakia",
    "Ukraine",
  ],
  Portugal: ["Spain"],
  Qatar: ["Saudi Arabia"],
  Romania: ["Bulgaria", "Hungary", "Moldova", "Serbia", "Ukraine"],
  Russia: [
    "Azerbaijan",
    "Belarus",
    "People's Republic of China",
    "Estonia",
    "Finland",
    "Georgia",
    "Kazakhstan",
    "North Korea",
    "Latvia",
    "Lithuania",
    "Mongolia",
    "Norway",
    "Poland",
    "Ukraine",
    "",
  ],
  Rwanda: ["Burundi", "Democratic Republic of the Congo", "Tanzania", "Uganda"],
  "Saint Kitts and Nevis": [""],
  "Saint Lucia": [""],
  "Saint Vincent and the Grenadines": [""],
  Samoa: [""],
  "San Marino": ["Italy"],
  "São Tomé and Príncipe": [""],
  "Saudi Arabia": [
    "Iraq",
    "Jordan",
    "Kuwait",
    "Oman",
    "Qatar",
    "United Arab Emirates",
    "Yemen",
  ],
  Senegal: ["The Gambia", "Guinea", "Guinea-Bissau", "Mali", "Mauritania"],
  Serbia: [
    "Bosnia and Herzegovina",
    "Bulgaria",
    "Croatia",
    "Hungary",
    "Kosovo",
    "Montenegro",
    "North Macedonia",
    "Romania",
  ],
  Seychelles: [""],
  "Sierra Leone": ["Guinea", "Liberia"],
  Singapore: [""],
  Slovakia: ["Austria", "Czech Republic", "Hungary", "Poland", "Ukraine"],
  Slovenia: ["Austria", "Croatia", "Italy", "Hungary"],
  "Solomon Islands": [""],
  Somalia: ["Djibouti", "Ethiopia", "Kenya"],
  "South Africa": [
    "Botswana",
    "Eswatini",
    "Lesotho",
    "Mozambique",
    "Namibia",
    "Zimbabwe",
  ],
  "South Ossetia[41]": ["Russia", "Georgia"],
  "South Sudan": [
    "Central African Republic",
    "Democratic Republic of the Congo",
    "Ethiopia",
    "Kenya",
    "Sudan",
    "Uganda",
  ],
  Spain: ["Andorra", "France", "Gibraltar", "Portugal", "Morocco"],
  "Sri Lanka": [""],
  Sudan: [
    "Central African Republic",
    "Chad",
    "Egypt",
    "Eritrea",
    "Ethiopia",
    "Libya",
    "South Sudan",
  ],
  Suriname: ["Brazil", "French Guiana", "Guyana"],
  Sweden: ["Finland", "Norway"],
  " Switzerland": ["Austria", "France", "Italy", "Liechtenstein", "Germany"],
  Syria: ["Iraq", "Israel", "Jordan", "Lebanon", "Turkey"],
  "Taiwan[42]": [""],
  Tajikistan: [
    "Afghanistan",
    "People's Republic of China",
    "Kyrgyzstan",
    "Uzbekistan",
  ],
  Tanzania: [
    "Burundi",
    "Democratic Republic of the Congo",
    "Kenya",
    "Malawi",
    "Mozambique",
    "Rwanda",
    "Uganda",
    "Zambia",
  ],
  Thailand: ["Cambodia", "Laos", "Malaysia", "Myanmar"],
  Togo: ["Benin", "Burkina Faso", "Ghana"],
  Tonga: [""],
  "Trinidad and Tobago": [""],
  Tunisia: ["Algeria", "Libya"],
  Turkey: [
    "Armenia",
    "Azerbaijan",
    "Bulgaria",
    "Georgia",
    "Greece",
    "Iran",
    "Iraq",
    "Syria",
  ],
  Turkmenistan: ["Afghanistan", "Iran", "Kazakhstan", "Uzbekistan"],
  Tuvalu: [""],
  Uganda: [
    "Democratic Republic of the Congo",
    "Kenya",
    "Rwanda",
    "South Sudan",
    "Tanzania",
  ],
  Ukraine: [
    "Belarus",
    "Hungary",
    "Moldova",
    "Poland",
    "Romania",
    "Russia",
    "Slovakia",
  ],
  "United Arab Emirates": ["Oman", "Saudi Arabia"],
  "United Kingdom": ["Ireland"],
  "United Kingdom (plus British overseas territories and Crown dependencies)\nshow\n→including:":
    ["Cyprus", "Ireland", "Spain"],
  "United States of America": ["Canada", "Mexico"],
  Uruguay: ["Argentina", "Brazil"],
  Uzbekistan: [
    "Afghanistan",
    "Kazakhstan",
    "Kyrgyzstan",
    "Tajikistan",
    "Turkmenistan",
  ],
  Vanuatu: [""],
  "Vatican City": ["Italy"],
  Venezuela: ["Brazil", "Colombia", "Guyana"],
  Vietnam: ["Cambodia", "People's Republic of China", "Laos"],
  "Western Sahara": ["Algeria", "Mauritania", "Morocco"],
  Yemen: ["Oman", "Saudi Arabia"],
  Zambia: [
    "Angola",
    "Botswana",
    "Democratic Republic of the Congo",
    "Malawi",
    "Mozambique",
    "Namibia",
    "Tanzania",
    "Zimbabwe",
  ],
  Zimbabwe: ["Botswana", "Mozambique", "South Africa", "Zambia"],
};
export default borderingCountries;
